### Create a new AddressBook
POST http://localhost:8080/addressbook
Content-Type: application/json

{
  "name": "MyAddressBook"
}

### Get AddressBook with id = 1
GET http://localhost:8080/addressbook/1
Accept: application/json

### Add a Buddy to AddressBook 1
POST http://localhost:8080/addressbook/1/buddy
Content-Type: application/json

{
  "name": "Damon",
  "phoneNumber": "613-236-2390",
  "address": "77 Maple Ave"
}

### Add another Buddy to AddressBook 1
POST http://localhost:8080/addressbook/1/buddy
Content-Type: application/json

{
  "name": "Stefan",
  "phoneNumber": "613-238-2986",
  "address": "44 Cook Street"
}

### Add another Buddy to AddressBook 1
POST http://localhost:8080/addressbook/1/buddy
Content-Type: application/json

{
  "name": "Kate",
  "phoneNumber": "613-348-5126",
  "address": "12 Island Drive"
}


### List all Buddies in AddressBook 1
GET http://localhost:8080/addressbook/1
Accept: application/json

### Delete Buddy with id = 1 from AddressBook 1
DELETE http://localhost:8080/addressbook/1/buddy/1

### List all AddressBooks
GET http://localhost:8080/addressbook
Accept: application/json

### View AddressBooks with id
GET http://localhost:8080/addressbook/1/view
Accept: application/json
